name: Sync Fork

on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: kishikawakatsumi
          base: main
          head: main
          auto_merge: false
          retries: 2
          retry_after: 10
          ignore_fail: true
